def create_tables():
    import class_cid
    myConnection = class_cid.connection
    cursor = myConnection.cursor()
    cursor.execute("use HMS")
    c_details = """CREATE TABLE IF NOT EXISTS C_DETAILS(CID VARCHAR(20) primary key,
            C_NAME VARCHAR(30),C_ADDRESS VARCHAR(30),C_AGE VARCHAR(30),C_COUNTRY VARCHAR(30) ,P_NO VARCHAR(30),C_EMAIL VARCHAR(30))"""
    cursor.execute(c_details)
    ROOM_RENT = """CREATE TABLE IF NOT EXISTS ROOM_RENT(CID VARCHAR(20) primary key,CHECK_IN DATE,CHECK_OUT DATE,
            ROOM_QUALITY VARCHAR(30),ROOM_CHOICE INT,NO_OF_DAYS INT,ROOMNO INT ,ROOMRENT INT)"""
    cursor.execute(ROOM_RENT)
    RESTAURENT = """CREATE TABLE IF NOT EXISTS RESTAURENT(ORDER_NO VARCHAR(20) primary key,CID VARCHAR(20),
            CUISINE_Choice VARCHAR(30),CUISINE VARCHAR(30),QUANTITY VARCHAR(30),BILL VARCHAR(30))"""
    cursor.execute(RESTAURENT)
    cursor.execute("""CREATE TABLE IF NOT EXISTS FASHION(ORDER_NO VARCHAR(20) primary key,CID VARCHAR(20),
            DRESS_CHOICE VARCHAR(30),DRESS VARCHAR(30),AMOUNT VARCHAR(30),BILL VARCHAR(30))""")
    TOTALBill = """CREATE TABLE IF NOT EXISTS TOTAL(CID VARCHAR(20) primary key,C_NAME VARCHAR(30),ROOMRENT INT ,
            RESTAURENTBILL INT ,GAMINGBILL INT,FASHIONBILL INT,TOTALAMOUNT INT)"""
    cursor.execute(TOTALBill)
    GAMING = """CREATE TABLE IF NOT EXISTS GAMING(ORDER_NO VARCHAR(20) primary key,CID VARCHAR(20),
               GAME_CHOICE VARCHAR(30),GAMES VARCHAR(30),HOURS VARCHAR(30),GAMING_BILL VARCHAR(30))"""
    cursor.execute(GAMING)
    cursor.close()